networks:
  default: localnet

  localnet:
    url: "http://127.0.0.1:4000/api"

  studionet:
    accounts:
      - "STUDIONET_PRIVATE_KEY_HERE"
      - "STUDIONET_PRIVATE_KEY_HERE"
      - "STUDIONET_PRIVATE_KEY_HERE"

paths:
  contracts: "contracts"

environment: .env
